[build]
target = "thumbv8m.main-none-eabihf"

[target.thumbv8m.main-none-eabihf]

rustflags = [
    "-C", "link-arg=-nmagic",
    "-C", "link-arg=-Tlink.x",
    "-C", "target-cpu=cortex-m33"
]

runner = "elf2uf2-rs -d -s -f rp2350-arm-s"